### ISSUE TITLE
Geen globals

### ISSUE THREAD

**Issue by MonikaaS** [JimvandeVen/web-app-from-scratch-18-19#1]
Van wat ik van de les van Joost heb begrepen is het gebruik van globale variabele slecht, omdat het conflicten kan veroorzaken met andere ingeladen code. Je zou je code in een iiffe kunnen stoppen, waarbij je code meteen runt, maar het niet in je globale state staat.

https://github.com/JimvandeVen/web-app-from-scratch-18-19/blob/3ccdd9a1b6f687bd02e79c85b1d6da245064956f/public/js/app.js#L3-L5

**Comment by maanlamp** [comment]
`let` en `const` genereren geen "globale" variabelen. Ze zijn globaal bruikbaar, maar worden niet op `window` gezet. Dit is prima hoor! :)

**Comment by MonikaaS** [comment]
Ahh thanks! Weer wat geleerd 🤓
