### ISSUE TITLE
Button niet in formulier

### ISSUE THREAD

**Issue by DanielvandeVelde** [JimvandeVen/web-app-from-scratch-18-19#2]
https://github.com/JimvandeVen/web-app-from-scratch-18-19/blob/3ccdd9a1b6f687bd02e79c85b1d6da245064956f/index.html#L54-L55

De button kan in het formulier staan.
Je kan het refreshen voorkomen met Javascript en [preventDefault](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)
Maar volgens mij kan dit ook door het `type=button` mee te geven.

**Comment by JimvandeVen** [comment]
will do thanks
